version: "3.8"

services:
  app:
    build: .
    container_name: quality-nexus-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn dev
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: quality_nexus

  mysql:
    image: mysql:8
    container_name: quality-nexus-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quality_nexus
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
